# Generated by Django 5.1.4 on 2025-01-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
